apiVersion: apps/v1
kind: Deployment
metadata:
  name: p-nodejs-testing-deployment
  namespace: production
  labels:
    app: nodejs-testing
    env: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: p-nodejs
      env: production
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: p-nodejs
        env: production
    spec:
      containers:
        - name: p-nodejs
          image: >-
            sultonyakbar/nodejs-app:1.0.0
          ports:
            - containerPort: 3000
              protocol: TCP
          resources:
            requests:
              cpu: "0.5m"    # 0.1 CPU core
              memory: "64Mi" # 128 MB memory
            limits:
              cpu: "1m"    # 0.2 CPU core
              memory: "128Mi" # 256 MB memory
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
          imagePullPolicy: Always
      restartPolicy: Always
      imagePullSecrets:
        - name: registry-secret
