apiVersion: v1
kind: Service
metadata:
  name: p-nodejs-service
  namespace: production
spec:
  externalTrafficPolicy: Local
  ports:
    - name: http
      nodePort: 31101
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: p-nodejs
  sessionAffinity: None
  type: LoadBalancer
